apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users
  labels:
    app: udagram-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-users
  template:
    metadata:
      labels:
        app: udagram-users
    spec:
      containers:
      - name: udagram-users
        image: genghong/udagram-users
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user
              key: db-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pwd
              key: db-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-db
              key: db-dbname
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: db-host
              key: db-hostname
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: aws-s3
              key: aws-bucket
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-rgn
              key: aws-region
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: aws-prof
              key: aws-profile
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: jwt-secret
        - name: URL
          valueFrom:
            secretKeyRef:
              name: server
              key: server-url                                            
        ports:
        - containerPort: 8080

